### ISSUE TITLE
Singend -> Unsigned

### ISSUE THREAD

**Issue by Sparagas** [Polymega/SilentHillDatabase#4]
In SH2 documentation there are a lot of signed integers in places like item count, there it clearly can't go to negative numbers.
Is this is an error, or do you clearly know you can't go to a negative number in a signed integer?

**Comment by JokieW** [comment]
Most signed variable are there by default if it's not clear that's it's signed (like addresses, offsets or counts)
The only real reason is that `int` is just a more common type than `unsigned int`

**Comment by mercury501** [comment]
To expand on what jokie said, it really wouldn't be a problem until the value reached 0x7FFFFF, which for the most part is unlikely, and going through all the addresses to mark them as unsigned would mean checking each one while testing the game, which would be very time consuming and prone to errors. Not to mention not very useful for reversing and modding. Closing this for now.
